### ISSUE TITLE
Fast Clear

### ISSUE THREAD

**Issue by Mathemmagician** [blaz-r/pi_pico_neopixel#4]
Not really an issue, more of a question.

What is the fastest way to clear the led lights?

Tried 2 things so far:

- `strip.fill( (  0,   0,   0) )` - very slow
- `strip.pixels = array.array("I", [0 for _ in range(strip.num_leds)])` - much faster, but seems hacky

**Comment by blaz-r** [comment]
Yeah, first of all _fill_ function uses _set_pixel_ function, which does quite a bit of shifting to set R, G and B components to right position in 32 bits, so this already makes it a bit slower. Then at the end it waits for 100 microseconds, which is used since neopixel protocol needs so called "latch time" at the end of transmission for color to "latch", but I realized that it's really useless here since no real "sending" is done, it's just filling the array, meaning that delay should only be present in _show_ function.

That "hacky" solution, would probably be the best way to do this, so if you want you can open a PR and implement _clear_ function that sets array with zeros directly this way. If you for any reason can't do that I'll fix this redundant delay and implement _clear_ function once I have a bit of time.

Thanks you for the question/issue :)

**Comment by Mathemmagician** [comment]
Cool, cool. Let me know if looks good to you https://github.com/blaz-r/pi_pico_neopixel/pull/5

**Comment by blaz-r** [comment]
Nice, thank you.
